# Site settings
title: 小模型测试
description: 小练习
# 好看的theme
theme: jekyll-theme-cayman

# GitHub Pages settings
remote_theme: pmarsceill/just-the-docs
# plugins:
#   - jekyll-feed
#   - jekyll-sitemap

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
